import Foundation
import shared

/// Fase 5, punto 5: el equivalente iOS del DataStore de Android (key `user_id`).
///
/// El backend identifica al usuario con el header `X-User-Id` en cada request; no hay
/// login todavia, asi que alcanza con un identificador estable por dispositivo. Se
/// genera una sola vez y queda en UserDefaults.
/// IMPORTANTE: aca NO se genera ningun id automatico. Antes lo hacia, y era un error:
/// el usuario acababa siendo un UUID recien inventado, sin historial ni favoritos en el
/// servidor, asi que "Mas escuchadas", "Tus generos favoritos" y "Recomendado para ti"
/// salian vacias. Android nunca inventa el id: `MainActivity` mira el DataStore y, si no
/// hay nada, arranca en `UserSetupScreen` para que la persona escriba su nombre. Aca se
/// hace exactamente igual.
enum UserIdStore {
    private static let key = "user_id"

    /// Identificador guardado, o cadena vacia si todavia no se configuro.
    static var current: String {
        UserDefaults.standard.string(forKey: key) ?? ""
    }

    /// Fija el userId. Sirve tambien para poner el mismo que ya usa el telefono Android
    /// y compartir favoritos e historial entre dispositivos.
    static func set(_ value: String) {
        UserDefaults.standard.set(value, forKey: key)
    }

    static func clear() {
        UserDefaults.standard.removeObject(forKey: key)
    }

    /// Un id guardado por la version anterior, que inventaba un UUID en el primer
    /// arranque. Ese usuario no existe en el servidor, asi que hay que descartarlo y
    /// pedir el nombre. Ningun nombre escrito por una persona tiene forma de UUID.
    static func isAutoGenerated(_ value: String) -> Bool {
        value.count == 36 && UUID(uuidString: value) != nil
    }
}

/// Equivalente del gate de `MainActivity`: decide si la app arranca en la pantalla de
/// bienvenida o directamente en Inicio.
@MainActor
final class UserSession: ObservableObject {

    static let shared = UserSession()

    @Published private(set) var userId: String

    var isConfigured: Bool { !userId.isEmpty }

    private init() {
        let saved = UserIdStore.current
        if UserIdStore.isAutoGenerated(saved) {
            // Migracion: se tira el UUID que invento la version anterior y se vuelve a
            // pedir el nombre, que es lo unico que hace aparecer historial y recomendadas.
            UserIdStore.clear()
            userId = ""
        } else {
            userId = saved
        }
    }

    /// Igual que el boton "Comenzar" de Android: si el campo esta vacio se usa "default".
    func setUser(_ name: String) {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        let value = trimmed.isEmpty ? "default" : trimmed
        UserIdStore.set(value)
        userId = value
    }
}

/// Adaptador del parametro `userIdProvider: suspend () -> String` de `MusicApiClient`.
///
/// Kotlin/Native exporta los tipos de funcion `suspend` como el protocolo
/// `KotlinSuspendFunction0`, cuyo unico metodo entrega el resultado por completion
/// handler. Como leer UserDefaults es sincronico, se responde en el acto.
final class UserIdProvider: NSObject, KotlinSuspendFunction0 {
    func invoke(completionHandler: @escaping (Any?, Error?) -> Void) {
        completionHandler(UserIdStore.current, nil)
    }
}
