org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35

# Fase 3 KMP: los targets iOS se compilan en el Mac (Xcode toolchain); en Windows/Linux se desactivan solos.
kotlin.native.ignoreDisabledTargets=true
